name: CI during commit
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build binary
        run: apt update && apt install -y g++ cmake make qt6-base-dev qt6-declarative-dev libxkbcommon-dev qml6-module-*
             mkdir build && cd build && cmake .. && make
